BEGIN TRANSACTION;
DELETE FROM "audit_ui";
DELETE FROM "clientes";
DELETE FROM "errores_sistema";
DELETE FROM "importaciones_temp";
DELETE FROM "proveedores";
DELETE FROM "roles";
INSERT INTO "roles" ("id", "name") VALUES (1, 'ADMIN');
INSERT INTO "roles" ("id", "name") VALUES (2, 'GERENTE');
INSERT INTO "roles" ("id", "name") VALUES (3, 'OPERADOR');
INSERT INTO "roles" ("id", "name") VALUES (4, 'INVITADO');
DELETE FROM "sucursales";
DELETE FROM "suppliers";
DELETE FROM "sync_outbox";
DELETE FROM "sync_queue";
DELETE FROM "devices";
DELETE FROM "permisos";
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (1, 'ADMIN', 'usuarios', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (2, 'ADMIN', 'seguridad', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (3, 'ADMIN', 'inventario', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (4, 'ADMIN', 'ventas', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (5, 'ADMIN', 'compras', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (6, 'ADMIN', 'pos', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (7, 'ADMIN', 'clientes', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (8, 'ADMIN', 'proveedores', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (9, 'ADMIN', 'reparaciones', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (10, 'ADMIN', 'transferencias', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (11, 'ADMIN', 'operaciones', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (12, 'ADMIN', 'reportes', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (13, 'ADMIN', 'auditoria', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (14, 'ADMIN', 'sincronizacion', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (15, 'ADMIN', 'respaldos', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (16, 'ADMIN', 'tiendas', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (17, 'ADMIN', 'actualizaciones', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (18, 'GERENTE', 'usuarios', 1, 1, 0);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (19, 'GERENTE', 'seguridad', 1, 1, 0);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (20, 'GERENTE', 'inventario', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (21, 'GERENTE', 'ventas', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (22, 'GERENTE', 'compras', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (23, 'GERENTE', 'pos', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (24, 'GERENTE', 'clientes', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (25, 'GERENTE', 'proveedores', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (26, 'GERENTE', 'reparaciones', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (27, 'GERENTE', 'transferencias', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (28, 'GERENTE', 'operaciones', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (29, 'GERENTE', 'reportes', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (30, 'GERENTE', 'auditoria', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (31, 'GERENTE', 'sincronizacion', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (32, 'GERENTE', 'respaldos', 1, 1, 0);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (33, 'GERENTE', 'tiendas', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (34, 'GERENTE', 'actualizaciones', 1, 1, 0);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (35, 'OPERADOR', 'usuarios', 1, 0, 0);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (36, 'OPERADOR', 'seguridad', 1, 0, 0);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (37, 'OPERADOR', 'inventario', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (38, 'OPERADOR', 'ventas', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (39, 'OPERADOR', 'compras', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (40, 'OPERADOR', 'pos', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (41, 'OPERADOR', 'clientes', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (42, 'OPERADOR', 'proveedores', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (43, 'OPERADOR', 'reparaciones', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (44, 'OPERADOR', 'transferencias', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (45, 'OPERADOR', 'operaciones', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (46, 'OPERADOR', 'reportes', 1, 1, 0);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (47, 'OPERADOR', 'auditoria', 1, 0, 0);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (48, 'OPERADOR', 'sincronizacion', 1, 1, 0);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (49, 'OPERADOR', 'respaldos', 1, 0, 0);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (50, 'OPERADOR', 'tiendas', 1, 1, 1);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (51, 'OPERADOR', 'actualizaciones', 1, 0, 0);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (52, 'INVITADO', 'usuarios', 0, 0, 0);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (53, 'INVITADO', 'seguridad', 0, 0, 0);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (54, 'INVITADO', 'inventario', 1, 0, 0);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (55, 'INVITADO', 'ventas', 1, 0, 0);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (56, 'INVITADO', 'compras', 0, 0, 0);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (57, 'INVITADO', 'pos', 0, 0, 0);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (58, 'INVITADO', 'clientes', 1, 0, 0);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (59, 'INVITADO', 'proveedores', 1, 0, 0);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (60, 'INVITADO', 'reparaciones', 0, 0, 0);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (61, 'INVITADO', 'transferencias', 0, 0, 0);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (62, 'INVITADO', 'operaciones', 0, 0, 0);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (63, 'INVITADO', 'reportes', 1, 0, 0);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (64, 'INVITADO', 'auditoria', 0, 0, 0);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (65, 'INVITADO', 'sincronizacion', 0, 0, 0);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (66, 'INVITADO', 'respaldos', 0, 0, 0);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (67, 'INVITADO', 'tiendas', 0, 0, 0);
INSERT INTO "permisos" ("id_permiso", "rol", "modulo", "puede_ver", "puede_editar", "puede_borrar") VALUES (68, 'INVITADO', 'actualizaciones', 0, 0, 0);
DELETE FROM "pos_configs";
DELETE FROM "pos_draft_sales";
DELETE FROM "repair_orders";
DELETE FROM "sync_attempts";
DELETE FROM "usuarios";
INSERT INTO "usuarios" ("id_usuario", "correo", "nombre", "telefono", "rol", "estado", "password_hash", "is_active", "fecha_creacion", "failed_login_attempts", "last_login_attempt_at", "locked_until", "sucursal_id") VALUES (1, 'xreason_admin_bc3ed539', 'Admin XReason', NULL, 'ADMIN', 'ACTIVO', '$pbkdf2-sha256$29000$tJaydk4pBYBwzllL6V2L8Q$xV7pJT5yIZjEZ0sGNU/YofKT.9WWWmpF0iyQMGT1tRE', 1, '2025-11-06T21:20:02.474135', 0, '2025-11-06T21:20:02.509205', NULL, NULL);
DELETE FROM "active_sessions";
INSERT INTO "active_sessions" ("id", "user_id", "session_token", "created_at", "last_used_at", "expires_at", "revoked_at", "revoked_by_id", "revoke_reason") VALUES (1, 1, 'e872f8451c8a4506906db8a2f5af653a', '2025-11-06T21:20:02.507723', '2025-11-06T21:20:02.652664', '2025-11-06T22:20:02.505616', NULL, NULL, NULL);
DELETE FROM "audit_alert_acknowledgements";
DELETE FROM "audit_logs";
INSERT INTO "audit_logs" ("id", "action", "entity_type", "entity_id", "details", "performed_by_id", "created_at") VALUES (1, 'user_created', 'user', '1', '{"description": "Usuario creado: xreason_admin_bc3ed539", "metadata": {"roles": ["ADMIN"]}}', NULL, '2025-11-06T21:20:02.482728');
INSERT INTO "audit_logs" ("id", "action", "entity_type", "entity_id", "details", "performed_by_id", "created_at") VALUES (2, 'auth_login_success', 'user', '1', '{"session_hint": "af653a"}', 1, '2025-11-06T21:20:02.511221');
DELETE FROM "cash_register_sessions";
DELETE FROM "compras";
DELETE FROM "customer_ledger_entries";
DELETE FROM "device_identifiers";
DELETE FROM "inventory_movements";
DELETE FROM "password_reset_tokens";
DELETE FROM "purchase_orders";
DELETE FROM "recurring_orders";
DELETE FROM "repair_order_parts";
DELETE FROM "stock_moves";
DELETE FROM "store_memberships";
DELETE FROM "supplier_batches";
DELETE FROM "sync_sessions";
DELETE FROM "transfer_orders";
DELETE FROM "user_roles";
INSERT INTO "user_roles" ("id", "user_id", "role_id") VALUES (1, 1, 1);
DELETE FROM "user_totp_secrets";
DELETE FROM "validaciones_importacion";
DELETE FROM "cost_ledger";
DELETE FROM "detalle_compras";
DELETE FROM "logs_sistema";
INSERT INTO "logs_sistema" ("id_log", "usuario", "modulo", "accion", "descripcion", "fecha", "nivel", "ip_origen", "audit_log_id") VALUES (1, NULL, 'usuarios', 'user_created', 'Usuario creado: xreason_admin_bc3ed539', '2025-11-06T21:20:02.483031', 'INFO', NULL, 1);
INSERT INTO "logs_sistema" ("id_log", "usuario", "modulo", "accion", "descripcion", "fecha", "nivel", "ip_origen", "audit_log_id") VALUES (2, 'xreason_admin_bc3ed539', 'usuarios', 'auth_login_success', 'session_hint: af653a', '2025-11-06T21:20:02.511440', 'INFO', NULL, 2);
DELETE FROM "purchase_order_items";
DELETE FROM "purchase_returns";
DELETE FROM "transfer_order_items";
DELETE FROM "ventas";
DELETE FROM "detalle_ventas";
DELETE FROM "sale_returns";
COMMIT;
