version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
      include: "scope"
    labels:
      - "ci"
      - "dependencies"
