frontend:
  - changed-files:
      - any-glob-to-any-file: ["frontend/**"]

backend:
  - changed-files:
      - any-glob-to-any-file: ["backend/**"]

docs:
  - changed-files:
      - any-glob-to-any-file: ["docs/**"]

ci:
  - changed-files:
      - any-glob-to-any-file: [".github/**"]

tests:
  - changed-files:
      - any-glob-to-any-file: ["frontend/**/__tests__/**", "backend/tests/**"]
